custom_topic_button_enabled:
  default: true
custom_topic_button_url:
  default: "/new-topic?title=Felhasználó értékelése&category=adok-veszek/ertekelesek"
custom_topic_button_title:
  default: "Értékelés"
custom_topic_button_label:
  default: "Értékelés írásához kattints ide"
custom_topic_button_icon:
  default: "star"
